# Generated by Django 5.2.11 on 2026-02-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_savingstransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='saved_amount',
        ),
    ]
