# Generated by Django 6.0.2 on 2026-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_savingsgoal_saved_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
